Repository ROBOTIS-GIT/ai_worker, pull requests merged in 2025-06, with the labels that each got.

#28 Update urdf and xacro files and modified the gazebo launch
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/launch/ffw_bg2_follower_gazebo.launch.py
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_description/urdf/common/follower/ffw_follower_body.xacro
  ffw_description/urdf/ffw_bg2_rev4_follower/ffw_bg2_follower.urdf
  ffw_description/urdf/ffw_bg2_rev4_follower/ffw_bg2_follower.urdf.xacro
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bug

#37 Bump 1.1.2
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_swerve_drive_controller/CHANGELOG.rst
  ffw_swerve_drive_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bump

#39 Bump 1.1.3
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/config/ffw_lg2_leader/ffw_lg2_leader_ai_hardware_controller.yaml
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_swerve_drive_controller/CHANGELOG.rst
  ffw_swerve_drive_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bump

#40 Add ros domain id to Dockerfile
  docker/Dockerfile
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_swerve_drive_controller/CHANGELOG.rst
  ffw_swerve_drive_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: enhancement

#41 Bump 1.1.4
  docker/Dockerfile
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_swerve_drive_controller/CHANGELOG.rst
  ffw_swerve_drive_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bump

#43 Bump 1.1.5
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_description/ros2_control/ffw_bg2_rev2_follower/ffw_bg2_follower.ros2_control.xacro
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_swerve_drive_controller/CHANGELOG.rst
  ffw_swerve_drive_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bump
