Repository ROBOTIS-GIT/ai_worker, pull requests merged in 2025-05, with the labels that each got.

#15 Update Dockerfile and ros2 control xacro file to enable async functionality
  docker/Dockerfile
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_description/ros2_control/ffw_leader_left_with_rh_system.ros2_control.xacro
  ffw_description/ros2_control/ffw_leader_right_with_rh_system.ros2_control.xacro
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bug, enhancement

#16 Bump 1.0.4
  docker/Dockerfile
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/package.xml
  ffw_description/ros2_control/ffw_leader_left_with_rh_system.ros2_control.xacro
  ffw_description/ros2_control/ffw_leader_right_with_rh_system.ros2_control.xacro
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bump

#18 Update camera URDF and Dockerfile
  docker/Dockerfile
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/meshes/follower/arm_l_link5.stl
  ffw_description/meshes/follower/arm_l_link6.stl
  ffw_description/meshes/follower/arm_l_link7.stl
  ffw_description/meshes/follower/arm_r_link5.stl
  ffw_description/meshes/follower/arm_r_link6.stl
  ffw_description/meshes/follower/arm_r_link7.stl
  ffw_description/package.xml
  ffw_description/urdf/follower/ffw_follower_body.urdf.xacro
  ffw_description/urdf/follower/ffw_follower_with_rh.urdf.xacro
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bug, enhancement

#19 Bump 1.0.5
  docker/Dockerfile
  ffw/CHANGELOG.rst
  ffw/package.xml
  ffw_bringup/CHANGELOG.rst
  ffw_bringup/package.xml
  ffw_bringup/setup.py
  ffw_description/CHANGELOG.rst
  ffw_description/meshes/follower/arm_l_link5.stl
  ffw_description/meshes/follower/arm_l_link6.stl
  ffw_description/meshes/follower/arm_l_link7.stl
  ffw_description/meshes/follower/arm_r_link5.stl
  ffw_description/meshes/follower/arm_r_link6.stl
  ffw_description/meshes/follower/arm_r_link7.stl
  ffw_description/package.xml
  ffw_description/urdf/follower/ffw_follower_body.urdf.xacro
  ffw_description/urdf/follower/ffw_follower_with_rh.urdf.xacro
  ffw_joint_trajectory_command_broadcaster/CHANGELOG.rst
  ffw_joint_trajectory_command_broadcaster/package.xml
  ffw_joystick_controller/CHANGELOG.rst
  ffw_joystick_controller/package.xml
  ffw_moveit_config/CHANGELOG.rst
  ffw_moveit_config/package.xml
  ffw_spring_actuator_controller/CHANGELOG.rst
  ffw_spring_actuator_controller/package.xml
  ffw_teleop/CHANGELOG.rst
  ffw_teleop/package.xml
  ffw_teleop/setup.py
Labels: bump

#24 Updated launch file to include frame prefix for leader in robot_state publisher and changed drive mode parameter
  README.md
  ffw_bringup/launch/ffw_lg2_leader_ai.launch.py
  ffw_description/ros2_control/ffw_bg2_rev4_follower/ffw_bg2_follower.ros2_control.xacro
Labels: enhancement
